### ISSUE TITLE
특정 클래스가 스캔되지 않음을 확인함.

### ISSUE THREAD

**Issue by LenKIM** [naver/scavenger#112]
사내 프로젝트에 도입 후 유용하게 사용중에 있습니다.

사용 중에 특정 클래스가 스캔되지 않음을 확인했습니다.

혹시 이렇게 될 수 있는 케이스가 있을까요?

사내 프로젝트라 구체적으로 공유하기 힘듭니다.
<img width="257" alt="image" src="https://github.com/naver/scavenger/assets/22192085/ea016c0e-1c16-4dcc-8d01-9b7b4359e7b5">

중간에 ContentBoostingController 가 있음에도 스캐빈저에서는 다음과 같이 노출중에 있습니다.

<img width="283" alt="image" src="https://github.com/naver/scavenger/assets/22192085/c86fb4b7-950c-4e06-bd6a-e99d4cd28805">

혹시 취해볼 수 있는 조치가 있을까요? 극히 제한적인 정보를 드려 죄송합니다. 

conf 의 패키지명은 맞게 설정되어 있습니다.

**Comment by taeyeon-Kim** [comment]
@LenKIM 안녕하세요. (_ _)
혹시 로컬에서도 재현된다면  conf 설정에 `debugMode`을 켜보시고 
`"[scavenger]  ~~~~.ContentBoostingController is scanned"`라는 로그가 찍히는지 확인해보겠어요??
