### ISSUE TITLE
Bulk download feature

### ISSUE THREAD

**Issue by sleeplesslord** [naver/scavenger#115]
I want to be able to download all the data in some standard format (e.g CSV, JSON) to do bulk processing, e.g grabbing all classes with some specific % of usage, finding all unused methods, etc. I couldn't find anything in the UI/docs/code, so I don't think this is supported.

1. Is this supported in some format right now?
2. If not supported, are there plans to support it in the future?

I would be up for writing a PR for this if it's something that the project would want

**Comment by sohyun-ku** [comment]
@sleeplesslord 

Hello, I think it releated to #61
you can export method invocation data like belows.
![image](https://github.com/naver/scavenger/assets/122586083/7596263d-2ada-4999-a581-0ec1babcee6d)

**Comment by taeyeon-Kim** [comment]
<img width="741" alt="image" src="https://github.com/naver/scavenger/assets/27491403/7927140f-135f-4b72-af60-85633ba1cd26">
@sleeplesslord   Currently you can download 'tsv' files on a snapshot basis.
Could this be related to your comment? Or are you suggesting a feature extension?

**Comment by sleeplesslord** [comment]
@sohyun-ku 
Yes, that's exactly what I'm looking for 🙏 it seems our scavenger instance is outdated, sorry about that!
