### ISSUE TITLE
@Log 문자열 연결 방식 문의

### ISSUE THREAD

**Issue by junhyeongkim2** [naver/scavenger#138]
안녕하세요 오픈소스 기여에 관심이 많은 학생입니다. 로깅 코드를 살펴보다가 궁금함을 참지 못하여 이슈를 올리게 되었습니다.

현재 코드 - CodeBaseScanner, Publisher 등
- @Log 어노테이션 사용
-  문자열 연결 방식으로 로깅 ("text" + variable)

제가 생각하는 문제점
- 문자열 연결 방식으로 인한 불필요한 연산 발생 (테스트 결과 파라미터 치환 방식 대비 25% 느림)
예)      log.info(
            "[scavenger] codebase(" + codeBase.getCodeBaseFingerprint() + ") scanned in "
                + (System.currentTimeMillis() - startedAt) + " ms: "
                + methods.size() + " methods"
        );
- @Log 보다 빠르고 고성능인 @Slf4j이 있음 (테스트 결과 약 5배 빠름)
- @Slf4j를 사용하게 되면 @Log에는 없는 파라미터 치환 방식을 통해서 가독성과 성능을 올릴 수 있을 것 같음
- 적은 차이라고 넘기기에는 많은 코드들에서 사용되는 log, 쌓이면 많은 성능 차이를 불러오지 않을까? 

제 얕은 지식으로는 이해하지 못하는 더 큰 그림이 있을 것 같은데 어떤 이유 때문에 @Log를 선택하시게 되셨는지 궁금합니다 🤔

**Comment by taeyeon-Kim** [comment]
@junhyeongkim2 안녕하세요. @slf4j를 사용하면  말씀주신장점들이 있지만 외부 의존성(로깅 프레임워크)이 필요하게됩니다.
스캐빈저 자바 에이전트에서는 최소한의 의존성을 가지고 client 자바 어플리케이션의 로깅 프레임워크 충돌을 없애기 위해 `java.util.logging`을 사용하는 @Log를 사용하게 됐습니다. 😄

**Comment by junhyeongkim2** [comment]
부족한 질문이었지만 친절하게 답변해 주셔서 감사드립니다! 궁금증이 잘 해결되었습니다 😄
