### ISSUE TITLE
Scavenger 동작 방식 문의

### ISSUE THREAD

**Issue by YongjoonSeo** [naver/scavenger#141]
안녕하세요. LINE+ 서용준입니다.
좋은 도구 만들어주셔서 고맙습니다.

저희 팀에서 Scavenger를 도입 중인데, 동작 방식이 잘 이해되지 않는 게 있어서 문의드립니다.

## 수집 주기 관련
1. 수집 스케줄러는 [agent](https://github.com/naver/scavenger/blob/1e9c0a4299e2c1a0215ed091c45d8b6fa8408195/scavenger-agent-java/src/main/java/com/navercorp/scavenger/javaagent/scheduling/Scheduler.java#L105-L121)에서 도는 거고 그 주기를 [collector](https://github.com/naver/scavenger/blob/1e9c0a4299e2c1a0215ed091c45d8b6fa8408195/scavenger-collector/src/main/kotlin/com/navercorp/scavenger/controller/AgentController.kt#L50)에서 정하는 것 같은데 제가 이해한 방식으로 동작하는 게 맞을까요?
2. 만약 1번이 맞다면, 왜 주기를 agent가 아니라 collector에서 정하는 건가요?
3. UI의 데이터 수집(스크린샷 참고)의 20분이라는 수집 주기는 어디서 정해지는 것인가요? `v1.1.2-p1` 버전 릴리즈의 jar파일을 직접 다운로드하여 실행했으므로 기본값을 사용하고 있습니다. [agent의 `intervalSeconds`는 600](https://github.com/naver/scavenger/blob/1e9c0a4299e2c1a0215ed091c45d8b6fa8408195/scavenger-agent-java/src/main/java/com/navercorp/scavenger/javaagent/scheduling/Scheduler.java#L60)으로 설정되고 [collector에서는 약 120초](https://github.com/naver/scavenger/blob/10a6deb354f4a8e6ec173173421c079fa8647bd8/scavenger-collector/src/main/kotlin/com/navercorp/scavenger/service/AgentService.kt#L86)로 설정되어있어 20분이라는 시간이 어떻게 나왔는지 궁금합니다.
![Scavenger UI 데이터 수집](https://github.com/user-attachments/assets/9bbfb57d-059d-4f5e-8962-a92e3546b43a)
4. Deview 데모에 보니까 `forceIntervalSeconds`를 conf 파일에 지정해서 사용하시던데, 수집 주기같은 걸 조정하기 위해선 이 scavenger.conf 파일에 설정해서 사용하는 걸 권하시나요? Scavenger UI에서 설정 파일을 생성했을 땐 해당 설정을 넣어주는 란이 안 보이더라고요. 
![Deview scavenger.conf demo](https://github.com/user-attachments/assets/dc676bb5-a008-4c4f-9cc4-cd7a141c29b8)
5. 수집 주기를 변경하고 싶다면 `forceIntervalSeconds`를 조절해서 사용하면 되나요?

## 호출 기록 보관 관련
1. collector에서는 gc 스케줄러가 돌면서 [일주일 정도 호출되지 않은 메서드는 제거](https://github.com/naver/scavenger/blob/10a6deb354f4a8e6ec173173421c079fa8647bd8/scavenger-collector/src/main/kotlin/com/navercorp/scavenger/service/GarbageCollectService.kt#L163)하는 것 같습니다. 적어도 한 달 이상 호출 기록을 보유한 다음 스냅샷을 생성해서 한 달 이상 미사용된 메서드인지 확인하려고 하는데, jar를 직접 실행하여 사용할 때도 호출 기록 보유 기간을 한 달 이상으로 설정할 수도 있나요?
2. 애플리케이션 재기동 시 JVM UUID가 새로 생기면서 에이전트 목록이 갱신되는 것 같았습니다. 애플리케이션 재기동 시기와 상관 없이 호출 기록을 볼 수 있는지 궁금합니다. 예를 들어, 12월 1일부터 호출 기록을 수집하고 있었고 12월 15일에 애플리케이션을 재기동하여 새로 JVM UUID가 만들어진 상황이라면 1일 부터의 스냅샷을 생성했을 때 **1일부터 현재까지의 메서드 호출 이력이 모두 반영되는 건가요?** (Scavenger UI상에서 재기동 이전의 JVM UUID가 얼마간 유지되다 사라지는 것 같은데, 스냅샷을 뜨는 시점은 이전 JVM UUID가 에이전트 목록에서 보이지 않은 때라고 가정합니다.)
3. 만약 2번이 맞다면, 에이전트 목록에는 보이지 않더라도 호출 기록은 DB에 저장되어있는 상태이므로 스냅샷으로 확인할 수 있다고 보면 되나요? / 만약 2번이 아니라면, 에이전트 목록에서 사라지면 해당 에이전트로부터 수집된 호출 기록은 DB에서도 모두 지워지는 건가요? 그 부분의 코드 흐름이 어떻게 되는지 알려주시면 감사하겠습니다.

## 기타
(+) 이건 개인적인 궁금증인데, [collector에서 약 120초](https://github.com/naver/scavenger/blob/10a6deb354f4a8e6ec173173421c079fa8647bd8/scavenger-collector/src/main/kotlin/com/navercorp/scavenger/service/AgentService.kt#L86)로 `invocationDataPublisherIntervalSeconds`가 정해진 곳에서 `Random.nextInt(10)`가 필요한 이유가 뭔가요?

고맙습니다.

**Comment by taeyeon-Kim** [comment]
@YongjoonSeo 안녕하세요 (_ _)

## 수집 주기 관련

1. 네 맞습니다.
2. collector가 agent들을 제어하기 위함이 있습니다. 이를 위해 agent에 대한 정보들을 db에 저장함으로써 UI상에도 노출을 할 수 있기도합니다
3. https://github.com/naver/scavenger/blob/1e9c0a4299e2c1a0215ed091c45d8b6fa8408195/scavenger-collector/src/main/kotlin/com/navercorp/scavenger/service/IntervalService.kt#L67-L79 를 보면 수집주기를 점점 늘리는 로직이 있습니다.
4. 해당 설정은 권고하지 않습니다. 해당 설정은 주로 디버깅을 위해 사용하는 옵션이긴합니다. 네이버 내의 서비스들에서도 수집 주기 설정은 따로 설정하지 않고 있습니다.
5. `forceIntervalSeconds`을 설정하면 됩니다만 해당 설정은 `4`의 답변처럼 권하지 않고 있습니다.


## 호출 기록 보관 관련
1. gc의 대상이 되는 메서드는 호출여부와 관계 없이 사용자 어플리케이션이 초기 코드베이스를 스캔되지 않는 메서드들에 대해서 삭제가 됩니다.
   해당 코드가 정말로 삭제가 안됐다면, 스냅샷을 언제 생성해도 확인이 가능합니다.

2. 메서드 삭제가 안됐다면 애플리케이션 재시동과 상관없이 호출 기록 확인이 가능합니다. 예를 들어주신 부분에 대한 답변은 1일부터 현재까지의 메서드 호출이력이 모두 반영됩니다.

3. 네 스냅샷으로 확인이 가능합니다.


## 기타

랜덤을 준 이유는 수십개의 에이전트가 동시에 코드베이스 정보, 메서드 호출 정보를 받지 않도록 하기위함이었습니다.


@sohyun-ku @kojandy 님 혹시 제가 답변을 잘못한 부분이 있다면.. 좀 더 코멘트 부탁드립니다. (_ _)

**Comment by YongjoonSeo** [comment]
친절하고 명료한 답변 고맙습니다 태연님.
혹시 그러면 메서드 호출 이력은 영구히 저장 되는 거로 생각해도 되는지요?
운영 환경에서 일부 서버에서만 샘플링하는 게 아니라 전 서버에서 메서드 호출 이력을 수집하는 것을 권하는 것으로 알고있는데, 지속해서 Scavenger를 운용한다고 하면 저장소(MySQL)의 용량이 부족할 수도 있을 것 같아 걱정이 되어 여쭙습니다. 통상 운영 환경에서 저장소 용량을 어느 정도로 두고 사용하시는지도 공유가 가능한가요?

**Comment by taeyeon-Kim** [comment]
@YongjoonSeo 님
https://github.com/naver/scavenger/blob/1e9c0a4299e2c1a0215ed091c45d8b6fa8408195/scavenger-collector/src/main/kotlin/com/navercorp/scavenger/service/GarbageCollectService.kt#L165-L174
에서 gc 동작 시 메서드 정보(method)와 해당 메서드의 호출(invocation) 이력도 같이 삭제하고 있습니다.
경험상 크게 mysql로 충분히 운영이 가능해 따로 산정을 해본적이 없습니다.
물론 네이버 내에서 vitess를 활용하고 있긴합니다. 관련한 설정도 https://github.com/naver/scavenger/tree/develop/scavenger-schema/vitess 에서 제공하고 있으니 vitess로의 분산 DB도 고려해볼수 있을 것 같습니다.

**Comment by YongjoonSeo** [comment]
@taeyeon-Kim 님 알려주셔서 고맙습니다! 많은 도움이 되었습니다 (_ _)

**Comment by YongjoonSeo** [comment]
@taeyeon-Kim 님 이 이슈에서 한 가지만 더 여쭙고자 합니다.
메서드가 지워지면 해당 메서드의 호출 기록도 함께 지워지는 로직은 이해했습니다.
혹시 Scavenger를 운용하면서 지워지지 않은 메서드의 오래된 호출 기록을 주기적으로 제거하는 등의 처리는 하지 않나요?

invocations 테이블의 레코드 하나당 용량이 대략 282 바이트정도 되는 것 같은데, Deview에서 살짝 언급하셨던 31만 2천개의 메서드가 있는 대형 서비스를 기준으로 한다면 최악의 경우(모든 메서드가 호출되는 경우) 한 번에 수집에 약 84MB의 용량을 차지하게 되는 것 같습니다. 만약 2분마다 수집된다고 가정하면 하루 약 60GB정도의 용량이 필요한데, 메서드가 지워지지 않는 한 영구적으로 호출 기록을 저장하게 되면 필요한 디스크 용량이 상당할 것 같아서 여쭙습니다. (물론 가장 부하가 큰 경우를 가정한 것이지만요)

**Comment by sohyun-ku** [comment]
@YongjoonSeo 

안녕하세요.

1. Scavenger의 호출 기록 삭제 여부
Scavenger를 운영하면서 호출 기록 데이터를 임의로 삭제하는 처리는 진행하지 않았습니다.

2. 호출 기록의 디스크 용량 관련
Invocation 수집 내역은 최초 1회 insert되고, 동일 메서드의 수집 내역이 반복될 경우 update로 처리됩니다. 따라서 모든 호출 내역이 계속 누적되어 새로운 레코드가 생성되지는 않습니다.

3. 인스턴스(에이전트) 개수와 저장 용량의 관계
저장 용량은 인스턴스(또는 에이전트) 개수에 비례하지 않습니다.
Scavenger는 메서드 수집 시 upsert로 동작하기 때문에 최초 데이터만 insert되고 이후 동일 메서드에 대해서는 update됩니다. 따라서 인스턴스 수가 증가해도 저장 용량은 크게 영향을 받지 않습니다.

https://github.com/naver/scavenger/blob/1e9c0a4299e2c1a0215ed091c45d8b6fa8408195/scavenger-collector/src/main/kotlin/com/navercorp/scavenger/service/CodeBaseImportService.kt#L26-L71
https://github.com/naver/scavenger/blob/1e9c0a4299e2c1a0215ed091c45d8b6fa8408195/scavenger-collector/src/main/kotlin/com/navercorp/scavenger/service/InvocationImportService.kt#L20-L59

cc. @taeyeon-Kim

**Comment by YongjoonSeo** [comment]
@sohyun-ku 님 답변 고맙습니다.
upsert되는 것으로 이해했는데, 여전히 석연치 않은 부분이 있습니다.
제가 구축한 Scavenger Collector의 methods 테이블에는 6,441개의 레코드가, invocations 테이블에는 15,093개의 레코드가 저장되어 있습니다. upsert 방식이라고 하면 환경 두 개에 대해 세팅해둔 상태라 6,441 * 2 = 12,882 개의 레코드만 있어야 할 것 같은데 2,211 개의 개수 차이가 있습니다. 중간에 메서드가 추가된 게 있다고 가정해도 2,211개는 너무 많은 것 같습니다. 어떤 게 이 개수 차이를 만들어내는 건가요?

**Comment by sohyun-ku** [comment]
@YongjoonSeo 

코멘트만으로는 정확한 원인을 특정하기는 어렵겠지만, 테이블 구조상 invocations 테이블은 methods 테이블에 비해 더 복잡한 제약 조건을 가지고 있습니다. 
이는 `customerId`, `applicationId`, `environmentId`, `signatureHash`의 조합에 의한 것으로, methods 테이블의 제약 조건인 `customerId`와 `signatureHash`에 대해 여러 `applicationId`와 `environmentId` 조합이 가능해집니다. 
이로 인해 invocations 테이블의 레코드 수가 더 많을 수 있습니다.
그 외의 세부적인 내용에 대해서는 직접 DB 데이터를 확인해주시면 감사하겠습니다

관련 내용을 이해하시는 데 도움이 될 만한 methods와 invocations 테이블의 스키마를 공유드립니다.
https://github.com/naver/scavenger/blob/1e9c0a4299e2c1a0215ed091c45d8b6fa8408195/scavenger-schema/src/main/resources/db/changelog/schema.sql#L91-L123

**Comment by YongjoonSeo** [comment]
@sohyun-ku 님 도움 주셔서 고맙습니다! (_ _)
