### ISSUE TITLE
한 어플리케이션에 대한 다수의 agent

### ISSUE THREAD

**Issue by BBlack-Hun** [naver/scavenger#42]
![스크린샷 2023-03-06 오후 12 00 31](https://user-images.githubusercontent.com/55784870/223009566-5fabd03f-d516-4e3d-91ff-b6deaf9da898.png)

scavenger 를 테스트해보고 있던 와중에 위의 이미지에서 볼 수 있듯이, 한 프로젝트에 대해 다수의 agent가 생성이 되는 것을 확인하였습니다.

agent 생성에 대한 언급을 document 에서 못본거 같아서 이러한 현상이 정상인지 궁금합니다.

**Comment by taeyeon-Kim** [comment]
@BBlack-Hun 안녕하세요.
정상적인 상황입니다. :)
어플리케이션이 실행 될 때마다 JVM UUID 부여되는데요. JVM UUID에 1:1에 대응하는 에이전트가 생성됩니다.
공유주신 스크린샷도 그에따라 여러 개가 생성된 것으로 보이는데요. 시간이 흐르면 collector에서 진행하는 GC에 의해 사용되지 않는 에이전트 목록은 삭제가 됩니다

**Comment by junoyoon** [comment]
태연님 말씀과 같이 여러번 띄우면 그때마다 JVM UUID 가 신규로 생성됩니다. 안쓰이는 JVM 은 시간을 몇시간내에 자동 삭제 됩니다.

**Comment by BBlack-Hun** [comment]
@taeyeon-Kim @junoyoon 
감사합니다!

제가 모니터링을 꾸준히 하고 있지 않아서, 사용하지 않는 JVM 들이 GC 들에 의해 삭제되는 것을 확인하지 못했던거 같습니다.

설명해 주셔서 정말 감사합니다.
