### ISSUE TITLE
configuration 문의

### ISSUE THREAD

**Issue by form-c** [naver/scavenger#44]
안녕하세요

scavenger 설정 해보고 있는데요. 

1. collector 실행   /  java -Dspring.profiles.active=h2 -jar scavenger-collector-boot.jar

2. api 실행  /   java -Dspring.profiles.active=h2 -jar scavenger-api-boot.jar

3. localhost:8081/scavenger 에서 conf파일 생성
3-1. conf - serverUrl = scavenger Collector인 https://localhost:8080 이 맞나요?

4. 테스트할  프로젝트에 pom.xml에 agent.java dependency 추가

5. 프로젝트 실행시 VM option에  -javaagent:path/to/scavenger-agent.jar , -Dscavenger.configuration=path/to/scavenger.conf 추가

6. 테스트 진행

잘 이해가 안 돼서.. 잘못된 부분 짚어 주시면 감사하겠습니다..!

**Comment by taeyeon-Kim** [comment]
@form-c 안녕하세요. :)

> 1. collector 실행 / java -Dspring.profiles.active=h2 -jar scavenger-collector-boot.jar

collector를  http,grpc 8080포트와 h2 file mode, tcp(9091 포트)로 실행합니다. 

> 2. api 실행 / java -Dspring.profiles.active=h2 -jar scavenger-api-boot.jar

api를 8081 포트로 실행합니다. h2는 collector에서 오픈한 tcp 포트로 접근합니다.


> 3. localhost:8081/scavenger 에서 conf파일 생성
3-1. conf - serverUrl = scavenger Collector인 https://localhost:8080/ 이 맞나요?

넵 에이전트 설정을 위해 conf 파일을 생성해야합니다. 
이때 말씀주신 serverUrl은 에이전트가 수집한 데이터를 collector로 전송하기 위한 설정입니다. 그러므로 1에서 실행한대로  `https://localhost:8080/`가 맞습니다.
설정에 대한 가이드는 [여기](https://github.com/naver/scavenger/blob/develop/doc/installation.md#build-agent)를 참고 부탁드립니다.

> 4. 테스트할 프로젝트에 pom.xml에 agent.java dependency 추가

의존성을 추가하기보다 테스트할 프로젝트를 실행할 머신에 아래 처럼 에이전트를 다운받아야 사용하기 편합니다.
```cli
curl https://repo1.maven.org/maven2/com/navercorp/scavenger/scavenger-agent-java/1.0.3/scavenger-agent-java-1.0.3.jar -L -o scavenger-agent.jar
```

> 5. 프로젝트 실행시 VM option에 -javaagent:path/to/scavenger-agent.jar , -Dscavenger.configuration=path/to/scavenger.conf 추가

네 맞습니다.

> 6. 테스트 진행

이제 스캐빈저를 사용하시면 됩니다 :)

**Comment by form-c** [comment]
java -Dscavenger.configuration=scavenger.conf -javaagent:scavenger-agent.jar -jar TestScavenger-1.0-SNAPSHOT.jar

위 명령어를 실행했을 때 아래 오류가 발생하는데요
세 개 파일 전부 같은 폴더에 있는 상태입니다.

원인 알 수 있을까요? 

Error: Could not find or load main class .configuration=scavenger.conf
Caused by: java.lang.ClassNotFoundException: /configuration=scavenger/conf

**Comment by form-c** [comment]
![image](https://user-images.githubusercontent.com/8588080/223426186-f6dbfcd6-315f-4fc1-962e-069e534db8ee.png)

**Comment by junoyoon** [comment]
h2 는 스케빈저를 로컬에서 평가하실때 편리하게 하기 위해 제공하는 것이구요.
정식으로 쓰실려면 mysql 이상을 사용하시는 것을 추천 드립니다.

**Comment by form-c** [comment]
@junoyoon mysql 이상이라고 하시면 SQLServer, Oracle 등으로도 가능한건가요?

**Comment by junoyoon** [comment]
mysql 과 vitess 를 지원합니다

**Comment by junoyoon** [comment]
mysql 과 vitess 를 지원합니다

**Comment by junoyoon** [comment]
@form-c 추가적인 질문이 없어 이슈 닫습니다.
