### ISSUE TITLE
Perform Grpc @Transactional Test

### ISSUE THREAD

**Issue by junoyoon** [naver/scavenger#49]
https://armeria.dev/docs/server-grpc/#blocking-service-implementation

여기보시면 Grpc 를 블록킹 호출로 전환하는 방법이 기재되어 있습니다.

기존 @Transactional 테스트 분리건을 테스트 해봅니다.

**Comment by sohyun-ku** [comment]
[apply-blocking-to-gRPC](https://github.com/naver/scavenger/tree/feature/apply-blocking-to-gRPC) branch에서 테스트해본 결과 gRPC를 블록킹 호출로 전환하더라도 테스트 환경에서 transactional이 지원되지 않습니다.

그 이유는 `@SpringBootTest`에서 `DEFINED_PORT` 옵션을 사용할 경우 아래 이유로 transactional이 지원되지 않는다고 합니다.
> https://docs.spring.io/spring-boot/docs/2.1.3.RELEASE/reference/html/boot-features-testing.html#boot-features-testing-spring-boot-applications
If your test is `@Transactional`, it rolls back the transaction at the end of each test method by default. However, as using this arrangement with either RANDOM_PORT or DEFINED_PORT implicitly provides a real servlet environment, the HTTP client and server run in separate threads and, thus, in separate transactions. Any transaction initiated on the server does not roll back in this case.

https://github.com/naver/scavenger/blob/e2b7935579aeaf51eadab286546261a65af93ebd/scavenger-collector/src/test/kotlin/com/navercorp/scavenger/support/AbstractMockMvcApiTest.kt#L18-L23

`@Transactional`이 지원되지 않으니 기존처럼 DB를 별도로 사용하거나 mock을 사용해 테스트를 진행해야할 것으로 보입니다.
