### ISSUE TITLE
config값 문의

### ISSUE THREAD

**Issue by kys9261** [naver/scavenger#84]
forceIntervalSeconds 이 값이 Deview 발표자료와 영상에서는 쓰인걸로 보이는데요
가이드 문서에는 나와있지 않은데 어떤역할을 하는지 알수있을까요?

**Comment by sohyun-ku** [comment]
@kys9261 

안녕하세요.
`forceIntervalSeconds` 옵션 사용 시 Agent(클라이언트)에서 Collector(서버)로 Codebase(코드 현황)과 inInvocation(호출 내역)을 보고하는 publish rate를 직접 조정할 수 있습니다.
해당 옵션을 사용하지 않을 시 서버에서 전달하는 기본 `intervalSeconds` 값을 사용하게 됩니다.
