### ISSUE TITLE
UNKNOWN: HTTP status code 413 / Request Entity Too Large

### ISSUE THREAD

**Issue by OhSeungho** [naver/scavenger#86]
프로젝트에 적용할 때 다음과 같은 에러가 발생합니다. Request의 grpc limit이 걸리는 것 같습니다.

```
ERROR [my-service,,] [] [my-service-f66875bd8-7rzlb:2023-08-16 11:19:13.861] [scavenger scheduler] [c.n.s.j.s.Scheduler:publishCodeBaseIfNeeded:180] [scavenger] codebase publish failed
sc.io.grpc.StatusRuntimeException: UNKNOWN: HTTP status code 413
invalid content-type: text/plain; charset=utf-8
headers: Metadata(:status=413,content-type=text/plain; charset=utf-8,content-length=50,date=Wed, 16 Aug 2023 02:19:10 GMT,server=envoy)
DATA-----------------------------
Status: 413
Description: Request Entity Too Large
```

규모가 큰 프로젝트에서도 사용할 수 있도록 API, Collector 서버의 리소스가 충분하다면 동작 가능하게 구현을 부탁드립니다. 감사합니다.

**Comment by sohyun-ku** [comment]
@OhSeungho 

안녕하세요.
요청주신 기능은 #82 이슈와 동일해보이며 현재 개발 예정입니다.
해당 기능 제공 전까지는 conf 파일 내 필터 기능을 이용해 추적 메소드를 줄여 사용 부탁드립니다. ( _ _ )
configuration 가이드 참고하시면 좋을 것 같아 url 남겨드립니다.

- configuration 가이드: https://github.com/naver/scavenger/blob/develop/doc/installation.md#configuration-2

**Comment by taeyeon-Kim** [comment]
안녕하세요. (_ _)

@sohyun-ku 님 말씀대로 method limit 제어 기능은 개발중에 있습니다.
별개로 max message size of gRPC의 기능은 이미 제공하고 있으니 가이드 확인 부탁드립니다.
- collector: https://github.com/naver/scavenger/blob/develop/doc/installation.md#installation
> To change the max message size of gRPC in Collector, change the setting below.
> - -Darmeria.max-message-size: 10MB by default
>     - Supports B, KB, MB, GB, and TB units. 

- agent: https://github.com/naver/scavenger/blob/develop/doc/installation.md#installation-2

> To change the max message size of gRPC in agent, change the setting below.
>   -  -Dscavenger.max-message-size: 10MB by default
>      -  Supports B, KB, MB, GB, and TB units.

**Comment by OhSeungho** [comment]
@sohyun-ku 필터기능 활용하겠습니다. 감사합니다.
@taeyeon-Kim max message size는 기존 이슈를 보고 사용하고 있습니다. 감사합니다.(참고로 현재 에러 발생중인 message size는 1300MB로 설정하여 사용하였습니다)

**Comment by kojandy** [comment]
@hyukjin-lee 안녕하세요,

[위 댓글](https://github.com/naver/scavenger/issues/86#issuecomment-1679973429)에 설명되어 있는 gRPC 메시지 용량 제한 옵션을 collector, agent 양측에서 설정한 후에도 해당 오류가 발생하는 것이 맞을까요?

**Comment by hyukjin-lee** [comment]
@kojandy 네 맞습니다. 양쪽에 2000MB 로 설정했고 -Dscavenger, -Darmeria 구분도 잘 했음에도 불구하고 약 7만개 메서드를 대상으로 했을 때 Entity Too Large 413 오류가 발생합니다. 현재는 1만3천개를 대상으로 스캔되도록 줄여서 사용 중입니다. 필요하신 정보가 있으시면 말씀 부탁드립니다

**Comment by hyukjin-lee** [comment]
@kojandy collector 에  `-Dcom.linecorp.armeria.defaultMaxRequestLength` 설정을 추가하니 해결되었습니다
