### ISSUE TITLE
UI : Package Naming Case Sensitivity Issue

### ISSUE THREAD

**Issue by hyukjin-lee** [naver/scavenger#93]
Hello,

We are currently using Scavenger in our legacy system. There are projects where package names are started with uppercase. It appears that on the Scavenger UI, the starting character's case (uppercase or lowercase) is used to distinguish between a package and a class.

Is there any possibility to improve this so that Scavenger only recognizes actual packages as packages, irrespective of the case of the starting character? This would help in ensuring more accurate identification and reduce confusion.

Thank you for your attention to this matter.

**Comment by sohyun-ku** [comment]
@hyukjin-lee 

Hi :)
This feature was implemented in #96.
It'll be included in release `v1.1.2`.
