### ISSUE TITLE
Data truncation: Data too long for column

### ISSUE THREAD

**Issue by namsic6460** [naver/scavenger#95]
안녕하세요, Scavenger 를 실무에서 적용하기 위해 환경을 구축하는 과정에서 스냅샷을 생성할 때 다음과 같은 에러가 발생하여 이슈로 올립니다.

Scavenger 는 1.1.1 버전을 사용중입니다
Collector/Api 는 JAVA 11 환경이며 AWS Ubuntu Linux 에 구축해두었습니다
DB 는 utf8/utf8_general_ci 로 다른 AWS Ubuntu Linux 에 구축해두었습니다
Agent 는 테스트를 위해 사내 컴퓨터를 이용하였으며 Windows 10 환경입니다

아레는 scavenger-api 에러 로그입니다
[error.txt](https://github.com/naver/scavenger/files/12646095/error.txt)

**Comment by namsic6460** [comment]
추가로 필요한 자료가 있다면 가능한 선에서 최대한 제공해드리겠습니다

**Comment by taeyeon-Kim** [comment]
https://github.com/naver/scavenger/blob/fe0b524ce81664406b38e96e566125c2124a9c98/scavenger-schema/src/main/resources/db/changelog/schema.sql#L155-L166
의 signature가 TEXT가 아닌 VARCHAR(1000)으로 제한되어 있어서 발생한 것으로 보입니다. (_ _)
이 부분 수정하도록 하겠습니다.
DB의  signature 타입을 TEXT로 변경해서 사용해보시겠어요??

**Comment by namsic6460** [comment]
네, 변경 후 스냅샷 생성 성공하였습니다. 감사합니다

**Comment by namsic6460** [comment]
아 이슈 확인하고 수정하셔야 하니 이슈는 다시 열어두겠습니다

**Comment by sohyun-ku** [comment]
#98 에서 작업 완료했습니다.
`v1.1.2` 릴리즈에 포함될 예정입니다 :)
