### ISSUE TITLE
정규식을 통한 클래스 필터링

### ISSUE THREAD

**Issue by namsic6460** [naver/scavenger#99]
안녕하세요, 현재 QueryDSL 을 사용하는 프로젝트에 Scavenger 를 적용해서 데이터를 확인하고 있습니다.
QueryDSL 을 사용하다보니 Q클래스가 필연적으로 생성되는데, 이 클래스들은 퍼센트를 확인할 필요가 없을 것 같습니다.
현재는 package 단위로만 필터링이 가능한 것으로 아는데, 정규식을 통해 클래스를 필터링하는 기능을 건의드리고 싶습니다. 가능할까요?

**Comment by sohyun-ku** [comment]
@namsic6460 

안녕하세요.
기다려주셔서 감사합니다.  제안해주신 정규 표현식을 통한 필터링 옵션은 `v1.1.3` 릴리즈에 포함될 예정입니다.


configuration | default | Description
-- | -- | --
excludeByRegex |   | Specifies regular expressions you want to exclude from tracking.<br> This option performs filtering on the result of packages - excludedPackages + additionalPackages.<br>As this may impact performance, so it is recommended to use package-level filtering wherever possible.<br>ex) ^com\.example\.exclude(\..*)?$
additionalByRegex |   | Specifies regular expressions excluded by annotations that you want to include in the scan.<br>This option may impact performance, so it is recommended to use package-level filtering wherever possible.<br>ex) ^com\.example\.additional(\..*)?$
